### ISSUE TITLE
Paging @bchavez :)

### ISSUE THREAD

**Issue by Mike-E-angelo** [bchavez/Coinbase.Commerce#19]
Hi @bchavez I hope you are OK with using your issues board to page you.  I am not sure of any other way to contact you.  I wanted to let you know that Coinbase is actively engaging users on their new forum board and I brought up the issue in which we were both participants here:

https://github.com/coinbase/coinbase-ios-sdk/issues/54

The new issue is here:
https://forums.coinbasecloud.dev/t/any-web2-support/745

I thought you would find that interesting and/or might want to participate in the discussion there.

Hope all is well for you out there! 👍

(Oh yeah, please close this thread upon receipt!)

**Comment by bchavez** [comment]
Hi @Mike-E-angelo, thank you but I don't remember the context of the problem anymore. It looks like the problem was reported 2-3 years ago. Coinbase APIs are a mess and a pain in the bacon to maintain. If you find a solution, please send a PR with the appropriate test case and I'll review it.

Otherwise, at this moment, currently, I don't have the time or energy to work with **Coinbase Tech Support** unless they pay me to help them resolve and debug their API issues. **_After all, I'm sure they are charging transaction fees that are originating from my open-source Coinbase API libraries for C#/.NET anyway._**

**Comment by Mike-E-angelo** [comment]
No worries @bchavez I thought I would mention it to be sure. :)

FWIW/BTW, I have this project (along with half of NuGet it seems 😁) mentioned in the acknowledgements of an application I recently released here:
https://alpha.starbeam.one/about/acknowledgements
